# Starter pipeline
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'AzureDevOps-GCPKube'
    command: 'get'
    arguments: 'pods'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


