name: remote ssh command
#on: [push]
on:
  push:
    branches:
       - master
       - test_gh_actions

jobs:

  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/staging.key
            chmod 600 ~/.ssh/staging.key
            cat >>~/.ssh/config << END
            Host gcpweb1
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
              ForwardAgent yes
      env:
            SSH_HOST: ${{ secrets.HOST }}
            SSH_USER: ${{ secrets.USERNAME }}
            SSH_KEY: ${{ secrets.KEY }}
            PROXY_SSH_HOST: ${{ secrets.PROXY_HOST }}
            GH_BRANCH: ${{ secrets.BRANCH }}

    - name: Check out the source
      run: ssh gcpweb1 'cd /home && /opt/git/bin/git fetch -a && /opt/git/bin/git checkout $GH_BRANCH && /opt/git/bin/git pull'
