name: remote ssh command
on: [push]
jobs:

  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/staging.key
            chmod 600 ~/.ssh/staging.key
            cat >>~/.ssh/config << END
            Host staging
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
            END
      env:
            SSH_HOST: ${{ secrets.HOST }}
            SSH_USER: ${{ secrets.USERNAME }}
            SSH_KEY: ${{ secrets.KEY }}
