name: remote ssh command
on:
  push:
    branches:
       - master
       - test_gh_actions

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GH_BRANCH: ${{ secrets.BRANCH }}
  SSH_KEY: ${{ secrets.KEY }}
  GCE_INSTANCE_ZONE: us-central1-a

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}
    - name: Deploy
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        HOSTIP=$(gcloud compute instances list --filter="name:datpiff-webapp*" --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
        PROXYIP=$(gcloud compute instances list --filter="name:datpiff-haproxy*" --format='get(networkInterfaces[0].accessConfigs[0].natIP)')

        #for i in $HOSTIP
        #do
        #    ssh -o StrictHostKeyChecking=no -i ~/.ssh/staging.key root@$i 'cd /home && /opt/git/bin/git fetch -a && /opt/git/bin/git checkout $GH_BRANCH && /opt/git/bin/git pull'
        #done

    - name: Checkout
      uses: lamarwhitej/sandbox@test_gh_actions

    - name: Update HAProxy Config
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        PROXYIP=$(gcloud compute instances list --filter="name:datpiff-haproxy*" --format='get(networkInterfaces[0].accessConfigs[0].natIP)')

        for i in $PROXYIP
        do
            gcloud compute scp README.md dapiff-haproxy-1113-vm:/home/joshuawhite/
            #scp -o StrictHostKeyChecking=no -i ~/.ssh/staging.key haproxy/haproxy.cfg root@$i:/root/haproxy.cfg
            #ssh -o StrictHostKeyChecking=no -i ~/.ssh/staging.key root@$i 'sudo cp haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg && sudo service haproxy reload'
        done
