name: remote ssh command
on:
  push:
    branches:
       - master
       - test_gh_actions

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: datpiff-webapp-1  # TODO: update to instance name
  GCE_INSTANCE_ZONE: us-central1-a   # TODO: update to instance zone

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}
    - name: Deploy
      run: |-
        gcloud compute instances list --filter="name:datpiff-webapp*"
