name: remote ssh command
on:
  push:
    branches:
       - master
       - test_gh_actions

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GH_BRANCH: ${{ secrets.BRANCH }}
  SSH_KEY: ${{ secrets.KEY }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}

    - name: Update Webapp Servers
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        for zone in us-central1-a us-central1-b us-central1-c us-central1-f
        do
            HOSTIP=$(gcloud compute instances list --zones=$zone --filter="name:datpiff-webapp*" --format='get(networkInterfaces[0].accessConfigs[0].natIP)')

            for i in $HOSTIP
            do
                ssh -o StrictHostKeyChecking=no -i ~/.ssh/staging.key root@$i 'cd /home && /opt/git/bin/git fetch -a && /opt/git/bin/git checkout $GH_BRANCH && /opt/git/bin/git pull'
            done
        done
    - name: Update HAProxy Config
      run: |
        for zone in us-central1-a us-central1-b us-central1-c us-central1-f
        do
            PROXYIP=$(gcloud compute instances list --zones=$zone --filter="name:datpiff-haproxy*" --format='get(NAME)')

            for i in $PROXYIP
            do
                gcloud compute scp --zone=$zone README.md $i:/tmp
                FILE_DIFF=$(gcloud compute ssh $i --zone=$zone --command="diff /tmp/README.md /etc/haproxy/README.md")

                #if [ ! -z $FILE_DIFF ]
                #then
                #    gcloud compute ssh $i  --zone=$zone --command="sudo mv /tmp/README.md /etc/haproxy"
                #fi
            done
        done
